import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-dvh flex justify-center w-full bg-[#fcf5e9] pt-4 pb-4">
        <div className="bg-[#b2d3e0] max-w-[480px] w-full min-h-[calc(100dvh-32px)] rounded-2xl p-4 overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}